// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using JadeNET5SignalR.Data;
using JadeNET5SignalR.Models;

namespace JadeNET5SignalR.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210118145103_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder
                .Entity<MachinesDataView>()
                .ToView(nameof(MachinesDataView))
                .HasKey(t => t.Workcenter);

            modelBuilder.Entity("JadeNET5SignalR.Models.MachinesDataView", b =>
            {
                b.Property<string>("Workcenter").HasColumnType("nvarchar(450)");
                b.Property<string>("Description").HasColumnType("nvarchar(450)");
                b.Property<string>("MachineState").HasColumnType("nvarchar(450)");
                b.Property<string>("Operator").HasColumnType("nvarchar(450)");
                b.Property<string>("OperatorId").HasColumnType("nvarchar(450)");
                b.Property<int>("OpStep").HasColumnType("int");
                b.Property<int>("OID").HasColumnType("int");
                b.Property<string>("Product").HasColumnType("nvarchar(450)");
                b.Property<int>("PartsRequired").HasColumnType("int");
                b.Property<int>("CycleCount").HasColumnType("int");
                b.Property<int>("PartsMade").HasColumnType("int");
                b.Property<int>("TotalPartsProduced").HasColumnType("int");
                b.Property<int>("FinalTotalPartsProduced").HasColumnType("int");
                b.Property<int>("CompletedQty").HasColumnType("int");
                b.Property<int>("PartsToGo").HasColumnType("int");
                b.Property<int>("LastGoodPartsId").HasColumnType("int");
                b.HasKey("Workcenter");
                b.ToTable("MachinesDataView");
            });

            modelBuilder.Entity("JadeNET5SignalR.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Cityname")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Employee");
                });

            modelBuilder.Entity("JadeNET5SignalR.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("TranType")
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Notification");
                });
#pragma warning restore 612, 618
        }
    }
}
